/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectInput = IDL.Record({
  'title' : IDL.Text,
  'githubLink' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'kaggleLink' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const ProjectId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Project = IDL.Record({
  'id' : ProjectId,
  'title' : IDL.Text,
  'githubLink' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'kaggleLink' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SocialLinks = IDL.Record({
  'linkedin' : IDL.Text,
  'email' : IDL.Text,
  'kaggle' : IDL.Text,
  'github' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'socialLinks' : SocialLinks,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProject' : IDL.Func([ProjectInput], [Project], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setProfile' : IDL.Func([Profile], [], []),
  'setSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateProject' : IDL.Func([ProjectId, ProjectInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectInput = IDL.Record({
    'title' : IDL.Text,
    'githubLink' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'kaggleLink' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Project = IDL.Record({
    'id' : ProjectId,
    'title' : IDL.Text,
    'githubLink' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'kaggleLink' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SocialLinks = IDL.Record({
    'linkedin' : IDL.Text,
    'email' : IDL.Text,
    'kaggle' : IDL.Text,
    'github' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'socialLinks' : SocialLinks,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProject' : IDL.Func([ProjectInput], [Project], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setProfile' : IDL.Func([Profile], [], []),
    'setSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateProject' : IDL.Func([ProjectId, ProjectInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };