/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Profile {
  'bio' : string,
  'title' : string,
  'socialLinks' : SocialLinks,
  'name' : string,
}
export interface Project {
  'id' : ProjectId,
  'title' : string,
  'githubLink' : string,
  'thumbnailUrl' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'updatedAt' : Timestamp,
  'kaggleLink' : string,
  'videoUrl' : string,
}
export type ProjectId = bigint;
export interface ProjectInput {
  'title' : string,
  'githubLink' : string,
  'thumbnailUrl' : string,
  'tags' : Array<string>,
  'description' : string,
  'kaggleLink' : string,
  'videoUrl' : string,
}
export interface SocialLinks {
  'linkedin' : string,
  'email' : string,
  'kaggle' : string,
  'github' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProject' : ActorMethod<[ProjectInput], Project>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSkills' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setProfile' : ActorMethod<[Profile], undefined>,
  'setSkills' : ActorMethod<[Array<string>], undefined>,
  'updateProject' : ActorMethod<[ProjectId, ProjectInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];